### ISSUE TITLE
Cannot use cross account access with SourceArn

### ISSUE THREAD

**Issue by jason-linthwaite** [aws/aws-sdk-rails#34] opened 2020-08-06 10:23 UTC
The SDK does not seem to allow setting the SourceArn and so we are unable to use this gem for cross account access.

It should be updated to allow using SourceArn when sending emails.

**Comment by mullermp** [comment] 2020-08-06 16:46
Hi, could I get some more information about what you are doing? Perhaps any code samples?

**Comment by nerixim** [comment] 2020-08-11 06:58
Hi @mullermp 
Found this issue while trying to set up cross account SES.

My use my use case is as follows (I guess same as @jason-linthwaite):
I have a production and a staging AWS accounts and I have my domain identity in the production account.
Now I want to send emails from my app placed in the staging account but I'm not sure if it's possible without using [aws-ses-sdk](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/SES/Client.html#send_raw_email-instance_method)

I'll try setting headers as described in SES docs. If it works as intended, maybe it's worth including in this gem's docs?
> you can include the following X-headers in the header of your raw email:
X-SES-SOURCE-ARN
X-SES-FROM-ARN
X-SES-RETURN-PATH-ARN

**Comment by mullermp** [comment] 2020-08-11 16:49
Ah I see, yeah, I think this could be supported. In [this method signature](https://github.com/aws/aws-sdk-rails/blob/15f77c3cc9bbf01fe33fb0d06589a29b9fe4b633/lib/aws/rails/mailer.rb#L27) we can add support for a hash `options = {}` that would be merged with `send_opts`. In that options hash you could supply any of those ARNs or future supported options.

**Comment by mullermp** [comment] 2020-08-11 21:35
@nerixim @jason-linthwaite I'm not sure if I can get those options passed into `send_raw_email`. Could you try sending the headers directly? 

```
message = MyMailer.send_email(...)
message['X-SES-SOURCE-ARN'] = 'arn:blahblah'
message.deliver
```

**Comment by mullermp** [comment] 2020-08-11 21:36
Just to clarify, are you all trying to set different ARNs per email or would they be the same per application?

**Comment by mullermp** [comment] 2020-08-11 22:30
I've updated the README on how to use those ARNs: https://github.com/aws/aws-sdk-rails/commit/ff06012a8ef33cb739553d0ef98d408c2c505ea0

I was able to test using X-SES-FROM-ARN. Can you verify that source ARN would work without needing to set the `:source` option in the API? The docs state it is optional if you specify a from address.

**Closed by mullermp** 2020-08-11 22:30 UTC
Labels: feature-request
